{% set name = "grype" %}
{% set version = "0.80.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: https://github.com/anchore/grype/archive/refs/tags/v{{ version }}.tar.gz
    sha256: 554b7e5fbc8c79e88475a77c47d1f4466d51880d922423cbffac132dd029fadd
  - url: https://gitlab.com/cznic/mathutil/-/raw/b13e5b5643328f15fd2fcedc85f647f0d8f9180f/LICENSE  # v1.5.0
    sha256: bfa9bf72a72ca009fd62a8f84fca3dca67e51d93af96352723646599898b6cf5
    fn: LICENSE-mathutil
  - url: https://raw.githubusercontent.com/xi2/xz/48954b6210f8d154cb5f8484d3a3e1f83489309e/LICENSE
    sha256: 5c640056d513f276d56635af7a0bed81cb7eac02a31b6e56d40c416557a8d8ce
    fn: LICENSE-xz

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('go-nocgo') }}
    - {{ stdlib('c') }}
    - go-licenses

test:
  commands:
    - grype --version | grep "{{ version }}" | grep -v grep

about:
  home: https://github.com/anchore/grype
  license: Apache-2.0
  license_family: Apache
  license_file:
    - LICENSE
    - library_licenses/
    - LICENSE-xz
    - LICENSE-mathutil
  summary: A vulnerability scanner for container images and filesystems

extra:
  recipe-maintainers:
    - janjagusch
