# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  version: "0.116.0"
  go_mod: github.com/anchore/grype
  go_cmd: ./cmd/grype
  go_bin: ${{ "$PREFIX/bin/grype" if unix else "%LIBRARY_BIN%\\grype.exe" }}
  go_build: go build -v -buildmode=pie -trimpath -modcacherw -ldflags="-X 'main.version=${{ version }}'"
  go_mod_mathutil: modernc.org/mathutil
  go_mod_xz: github.com/xi2/xz
  go_mod_magic: github.com/deitch/magic
  go_mod_attestation: github.com/in-toto/attestation
  license_ignores: ${{ go_mod }} ${{ go_mod_mathutil }} ${{ go_mod_xz }} ${{ go_mod_magic }} ${{ go_mod_attestation }}

package:
  name: grype
  version: ${{ version }}

source:
  - url: https://github.com/anchore/grype/archive/refs/tags/v${{ version }}.tar.gz
    sha256: 5e8aa8cf1ae21e46f1f5aa8349af1416153a9a3299cd80f5bb1ef38fd9d38252
    target_directory: ${{ go_mod }}
  - url: https://gitlab.com/cznic/mathutil/-/raw/b13e5b5643328f15fd2fcedc85f647f0d8f9180f/LICENSE  # v1.5.0
    sha256: bfa9bf72a72ca009fd62a8f84fca3dca67e51d93af96352723646599898b6cf5
    target_directory: library_licenses_manual/${{ go_mod_mathutil }}
  - url: https://raw.githubusercontent.com/xi2/xz/48954b6210f8d154cb5f8484d3a3e1f83489309e/LICENSE
    sha256: 5c640056d513f276d56635af7a0bed81cb7eac02a31b6e56d40c416557a8d8ce
    target_directory: library_licenses_manual/${{ go_mod_xz }}
  - url: https://raw.githubusercontent.com/deitch/magic/2def47b612f6f806d1e136bbec1c34fdefacf04a/LICENSE
    sha256: 2423c6eb9948e617a61f7a2d1cb463c69d60e599fbae5931551631d2a8730838
    target_directory: library_licenses_manual/${{ go_mod_magic }}
  - url: https://raw.githubusercontent.com/in-toto/attestation/refs/tags/v1.2.0/LICENSE
    sha256: b3a6ac899861c2c28a1abd5c7ea8733fefaed6938d730e099c42671386032aeb
    target_directory: library_licenses_manual/${{ go_mod_attestation }}

build:
  number: 0
  script:
    - ${{ "export" if unix else "set" }} "GOPATH=${{ SRC_DIR }}"
    - cd ${{ go_mod }}
    - go-licenses save ${{ go_cmd }} --save_path "${{ SRC_DIR }}/library_licenses" {% for i in license_ignores | split %}--ignore ${{ i }} {% endfor %}
    - ${{ go_build }} -o "${{ go_bin }}" ${{ go_cmd }}

requirements:
  build:
    - ${{ compiler('go-nocgo') }}
    - go-licenses

tests:
  - script:
      - grype --version | ${{ "grep" if unix else "findstr" }} "${{ version }}"

about:
  license: Apache-2.0
  license_file:
    - ${{ go_mod }}/LICENSE
    - library_licenses/
    - library_licenses_manual/
  summary: A vulnerability scanner for container images and filesystems
  homepage: https://github.com/anchore/grype

extra:
  recipe-maintainers:
    - janjagusch
    - fhoehle
